# ── DynamoDB — Pipeline Run State ───────────────────────────────────────────
# Primary key: run_id (String) — UUID generated by FastAPI on POST /api/v1/analyze
#
# Item shape (written by Lambda, read by frontend polling):
#   run_id        String  — UUID
#   created_at    String  — ISO-8601 timestamp
#   status        String  — RUNNING | COMPLETE | ERROR
#   agent_1_status  String  — IDLE | RUNNING | COMPLETE | ERROR
#   agent_2_status  String  — IDLE | RUNNING | COMPLETE | ERROR
#   agent_3_status  String  — IDLE | RUNNING | COMPLETE | ERROR
#   hex_events_key  String  — S3 key for Agent 1 output (results/{run_id}/hex_events.json)
#   threat_map_key  String  — S3 key for Agent 2 output (results/{run_id}/threat_map.json)
#   dispatch_plan_key String — S3 key for Agent 3 output (results/{run_id}/dispatch_plan.json)
#   tokens_used   Number  — cumulative Bedrock token count
#   duration_ms   Number  — wall-clock ms for full pipeline
#   error_message String  — populated on ERROR status

resource "aws_dynamodb_table" "pipeline_runs" {
  name         = "${local.prefix}-pipeline-runs"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "run_id"

  attribute {
    name = "run_id"
    type = "S"
  }

  # TTL: auto-delete runs older than 7 days — keeps the table lean for the demo
  ttl {
    attribute_name = "expires_at"
    enabled        = true
  }

  point_in_time_recovery {
    enabled = true
  }

  server_side_encryption {
    enabled = true
  }
}
